### ISSUE TITLE
The issue with the scope of the findings

### ISSUE THREAD

**Issue by emanjavacas** [fbkarsdorp/deepflow-analysis#10]
- In the general discussion, I feel the findings could be positioned somewhat more broadly. What do we learn from this study beyond the generation of rap lyrics? The authors very briefly touch upon this, but the discussion remains at a somewhat high level. Could these models also work for the generation of other forms of poetry? There has been some work on this, for example, on the generation of haikus. I am not sure, but don't think it is true that computer-generated haikus are difficult to distinguish from human authored haikus, at least until recently (and note that these are very short as well, like the rap fragments studied in this paper). Also: do you think there are practical benefits for computer-generated rap lyrics? And, if so, should rappers acknowledge using tools like these for their lyrics? (I am sure the authors are aware of the controversy surrounding rappers who allegedly don't write their own lyrics, like Drake or Dr. Dre.)

**Comment by emanjavacas** [comment]
- I think that the conditional model could be used for the generation of other forms of poetry. An interesting comparison would be to check whether rhyming based on conditions improves quality over rhyming through forceful decoding (through a process like this https://aclweb.org/anthology/P17-1016). The point being that in forceful decoding, the model might end up in an unstable state, while using conditions should be more harmonious.
- "do you think there are practical benefits for computer-generated rap lyrics?" Probably not...?

**Comment by mikekestemont** [comment]
-> "An interesting comparison would be to check whether rhyming based on conditions improves quality over rhyming through forceful decoding" -> That would be nice to show.

**Comment by fbkarsdorp** [comment]
A bit more reflection on applications (like poetry generation and lyric generation in general) seems like a good idea.

**Comment by fbkarsdorp** [comment]
I've added more reflection and contextualization at several places in the general discussion and the conclusion. Have a look.
