### ISSUE TITLE
Literature list

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/deepflow-analysis#2]
-   [Stay On-Topic: Generating. Context-specific Fake Restaurant Reviews](https://arxiv.org/pdf/1805.02400.pdf)
-   [The anatomy of online deception: what makes automated text convincing?](https://ora.ox.ac.uk/objects/uuid:a22ff288-8f27-457a-860b-c06337ee3d73)
-   [Enter the Robot Journalist: Users' perceptions of automated content](http://www.diva-portal.org/smash/get/diva2:699641/FULLTEXT01.pdf)
-   [Readers' perception of computer-generated news: Credibility, expertise, and readability](http://www.looooker.com/wp-content/uploads/2016/10/Readers-perception-of-computer-generated-news.pdf)
-   [Evaluating the text quality, human likeness and tailoring component of PASS: A Dutch data-to-text system for soccer](http://www.aclweb.org/anthology/C18-1082)
-   [Evaluation methodologies in Automatic Question Generation 2013-2018](http://www.aclweb.org/anthology/W18-6537)
-   [Survey of the State of the Art in Natural Language Generation: Core tasks, applications and evaluation](https://www.jair.org/index.php/jair/article/download/11173/26378)

The last one is especially good. Solid section about creative NLG and NLG evaluation.

**Comment by fbkarsdorp** [comment]
Some more references on similar projects as ours:

- [Guess Who? Multilingual Approach For The Automated Generation Of Author-Stylized Poetry](https://arxiv.org/pdf/1807.07147.pdf)
  Paper on author-style language generation
- [A Survey on Intelligent Poetry Generation: Languages, Features, Techniques, Reutilisation and Evaluation](http://www.aclweb.org/anthology/W17-3502)
  Solid overview of poetry generation systems
- [Your Paper has been Accepted, Rejected, or whatever: Automatic Generation of Scientific Paper Reviews](https://arts.units.it/retrieve/handle/11368/2880143/115785/2016-CDARES-PaperReviewGeneration.pdf)
  Another experiment in generating X.
- [Deep creations: Intellectual property and the automata](https://www.frontiersin.org/articles/10.3389/fdigh.2017.00003)
  On copyright issues
- [Evaluating Creative Language Generation: The Case of Rap Lyric Ghostwriting](https://arxiv.org/pdf/1612.03205.pdf)
  On the evaluation of creative writing generation
- [Natural Language Statistical Features of LSTM-generated Texts](https://arxiv.org/pdf/1804.04087.pdf)
  Paper on linguistic properties of LSTM-based generated text.

**Comment by emanjavacas** [comment]
You might want to look into this one: [Assessing the Stylistic Properties of Neurally Generated Text in
Authorship Attribution](http://aclweb.org/anthology/W17-4914), which is older than "Natural Language Statistical Features of LSTM-generated Texts" but didn't get any credit from them.

:-p

**Comment by fbkarsdorp** [comment]
Dead link. But that one's yours, right?

**Comment by emanjavacas** [comment]
I've fixed the link. Yup.

**Comment by fbkarsdorp** [comment]
Nice. From quickly skimming it, it seems our paper is a bit of an extension of your earlier work. Perhaps we can take your intro as a model for the introduction of the paper? Are you back at work, btw?

**Comment by emanjavacas** [comment]
yup I am back at work, I guess we could at least cite it (and get me an extra citation, yeah!)

**Comment by fbkarsdorp** [comment]
Cool. I've started working on the paper again. Will continue tomorrow with the experimental setup, and rewriting the stats analysis with the new features. After that we could try to tackle the introduction.

**Comment by mikekestemont** [comment]
On recognizing "real" Dada art
http://www.cs.cornell.edu/~laurejt/papers/dada-preprint.pdf
