### ISSUE TITLE
The issue of Hip-Hop lyrics vs rap lyrics

### ISSUE THREAD

**Issue by emanjavacas** [fbkarsdorp/deepflow-analysis#5]
- The next point is a detail, but might be worth clarifying nevertheless: why do you speak of Hip-Hop lyrics and not rap lyrics? I guess the latter term would be more appropriate, since Hip-Hop, at least traditionally, refers to a culture, which obviously includes rapping, but also, for example, graffiti and breakdancing.

**Comment by emanjavacas** [comment]
Fine by me. We could just change it.

**Comment by fbkarsdorp** [comment]
True. Easy.

**Comment by fbkarsdorp** [comment]
Fixed.
