### ISSUE TITLE
The issue with using semantic coherence measures

### ISSUE THREAD

**Issue by emanjavacas** [fbkarsdorp/deepflow-analysis#8]
Judging a snippet of several lines of lyrics seems like a very hard task if there is no context. I can imagine the original position within the song of the snippet is very important for the rate of success for classifying it as real. A snippet from the beginning of a verse might for instance seem more coherent than a snippet from the middle. It seems to me that semantic coherence is the main driver for succesful classification. In fig 1b for instance you would not make your choice based on linguistic features but rather on coherence of the text. I would like to see more analyis on semantic coherence and which role it plays.

**Comment by emanjavacas** [comment]
We can discuss this in #7

**Comment by fbkarsdorp** [comment]
Discussed in #7
