### ISSUE TITLE
The issue with evaluation task set up

### ISSUE THREAD

**Issue by emanjavacas** [fbkarsdorp/deepflow-analysis#9]
Another issue is that we don't really get an idea how well this particular architecture works. Adding a baseline model that uses a very simple language model could tell us something on where to place the quality of outputs of these more sophisticated models. This might be something for the discussion.

**Comment by emanjavacas** [comment]
I would consider the uncoditioned character-level model to be that baseline. It's a bit tiresome to be referred to count-based language models all the time, while it's already pretty clear that they are outperformed by recurrent models these days...

**Comment by mikekestemont** [comment]
I agree with your take on this: perhaps we can make this view explicit?

**Comment by fbkarsdorp** [comment]
Yes, let's make it explicit that the character model is the baseline + add a reference showing the superiority of that baseline as compared to simpler models.

**Comment by fbkarsdorp** [comment]
Could you add this, @emanjavacas?
